<?php

class ZwischentController extends Controller {

    public function populate() {
        $allfilms = array(
                        '10000 BC',
                        '101 dalmatas',
                        '1492',
                        '2 Guns',
                        '2012',
                        '28 Days',
                        '36 Chambers of Shaolin',
                        '7 días en La Habana',
                        '9',
                        'A beautiful mind',
                        'A christmas story',
                        'A league of their own',
                        'Adaptation',
                        'Adventures of Tin Tin',
                        'After earth',
                        'Air',
                        'Aladdin',
                        'Alice in Wonderland',
                        'Amadeus',
                        'Amelie',
                        'American gangster',
                        'American sniper',
                        'Anger management',
                        'Annie',
                        'Apocalypto',
                        'Arielle',
                        'Art of War II',
                        'Art of war III',
                        'Asterix and the Vikings',
                        'Asterix und Obelix',
                        'Avatar',
                        'Back to the future',
                        'Back to the future II',
                        'Back to the future III',
                        'Bad Boys',
                        'Battleship',
                        'Bear brothers',
                        'Beautiful girls',
                        'Beauty and the beast',
                        'Beginner Ganster',
                        'Beverly Hills Ninja',
                        'Blue Lagoon',
                        'Blues Brothers',
                        'Boomerang',
                        'Boulevard',
                        'Bridgit Jones Diary',
                        'Buena Vista Social Club',
                        'Burn after reading',
                        'Cars',
                        'Carstoons',
                        'Casablanca',
                        'Casino',
                        'Casualties of war',
                        'Catch me if you can',
                        'Center stage',
                        'Chamaco',
                        'Charlottes web',
                        'Chocolat',
                        'Cider House rules',
                        'City of blinds',
                        'Cloud Atlas',
                        'Cloudy with a chance of meatball',
                        'Colour of the night',
                        'Coming to America',
                        'Couch whispering',
                        'Cowboys & Aliens',
                        'Crazy, stupid, love',
                        'Curious Case of Benjamin Button',
                        'Date night',
                        'Death at a funeral',
                        'Death becomes her',
                        'Dejá vu',
                        'Demolition man',
                        'The Butler',
                        'Despicable me',
                        'Despicable me II',
                        'Dick Tracy',
                        'Die Ordnung der Schöpfung',
                        'Die Vampirschwestern',
                        'Dirty Dance II',
                        'District 9',
                        'Django unchained',
                        'Dragon War',
                        'Dreamgirls',
                        'Duplicity',
                        'EMotion',
                        'ET',
                        'Eat pray love',
                        'Falling in love',
                        'Familiar enemy',
                        'Finding Nemo',
                        'Flight',
                        'Focus',
                        'Frozen',
                        'Gandhi',
                        'Get smart',
                        'Gijoe',
                        'Gladiator',
                        'Gone with the winds',
                        'Good Bye Lenin',
                        'Good morning Viet Nam',
                        'Green Mile',
                        'Gremlins',
                        'Grown ups',
                        'Gullivers travels',
                        'HOP',
                        'Hancock',
                        'Hangover',
                        'Hangover 2',
                        'Hangover 3',
                        'Hannibal',
                        'Happy feet',
                        'Harry Potter and the order of Fenix',
                        'Harry Potter and tht gobblet of fire',
                        'Hellow Hemingway',
                        'Hercules',
                        'Home',
                        'Home Alone',
                        'Honig in Kopf',
                        'Hook',
                        'Horrible boses',
                        'Hotel Ruanda',
                        'Hotel transilvania',
                        'Hotel transilvania II',
                        'Hugo',
                        'I am a legend',
                        'Ice Age',
                        'Ice Age - Down of the dinosaurs',
                        'Ice Age - II',
                        'Identity',
                        'Imagine that',
                        'Inception',
                        'Indiana Jones - raiders of the lost ark',
                        'Indiana Jones and the last crusade',
                        'Indiana Jones and the temple of doom',
                        'Inglorious Bastards',
                        'Inside Hollywood',
                        'Inside Man',
                        'Intern',
                        'Iron Man I',
                        'Iron Man II',
                        'Iron Man III',
                        'Its complicated',
                        'Jacob the liar',
                        'Jenseits der Stille',
                        'Johny English',
                        'Journey to misterious island',
                        'Journey to the center of the earth',
                        'Julie & Julia',
                        'Jumper',
                        'Jurasic Park',
                        'Jurasic Park II',
                        'Jurasic Park III',
                        'Kein Ohr Hase',
                        'Kinky boots',
                        'Klick',
                        'Kung fu Panda',
                        'LA Crash',
                        'La Boheme',
                        'La vita e bella',
                        'Lake House',
                        'Las doce sillas',
                        'Last vegas',
                        'Legends of the Fall',
                        'Legion',
                        'Like the first time',
                        'Lions and lambs',
                        'Little focker',
                        'Little women',
                        'Looking for a friend for the end of the world',
                        'Lord of War',
                        'Lord of the Rings - The two towers',
                        'MIB',
                        'Madagascar',
                        'Madagascar II',
                        'Makellos',
                        'Maos last dancer',
                        'Matrix',
                        'Matrix revolutions',
                        'Medicus',
                        'Men in Black II',
                        'Metro',
                        'Minion short films',
                        'Minions',
                        'Miss Potter',
                        'Mission impossible II',
                        'Monster Inc',
                        'Monsters vs Aliens',
                        'Mrs Doubtfire',
                        'Mulan',
                        'Muppet Christmas movie',
                        'Murdered in the priest house',
                        'Music and Lyrics',
                        'New in Town',
                        'Night at the museum',
                        'Night at the museum II',
                        'Nine',
                        'Norbit',
                        'Nummer 5 lebt',
                        'Oblivion',
                        'On burning earth',
                        'Once upon a time in America',
                        'Open Season II',
                        'Open season',
                        'Open season III',
                        'Out of time',
                        'Over the hedge',
                        'Peter Pan',
                        'Pirates of the caribbean I',
                        'Pirates of the caribbean II',
                        'Pixar short films',
                        'Planet 51',
                        'Prince of Persia',
                        'Prometheus',
                        'Public Enemies',
                        'Pulp Fiction',
                        'Pursuit of happyness',
                        'Puss in Boots',
                        'Rapunzel',
                        'Rat Race',
                        'Ray',
                        'Red lights',
                        'Redemption',
                        'Regreso a itaca',
                        'Reign over me',
                        'Ricky and the flash',
                        'Ride along',
                        'Righteous Kill',
                        'Rio',
                        'Rocknrolla',
                        'Rumors has it',
                        'Safe house',
                        'Salsa',
                        'Scarface',
                        'Scent of a woman',
                        'Sea of love',
                        'Sense and sensibility',
                        'Seven lifes',
                        'Sex and the City',
                        'Sex and the City II',
                        'Shaft',
                        'Shrek the third',
                        'Skyfall',
                        'Sleepless in Seatle',
                        'Snow White',
                        'Somewhere in Mexico',
                        'Spanglish',
                        'Spider Man',
                        'Startdust',
                        'Stealth',
                        'Steel magnolias',
                        'Stepmom',
                        'Super 8',
                        'Taking of Pelham',
                        'Tears of the sun',
                        'The 13 warrior',
                        'The 200 years man',
                        'The American',
                        'The Champ',
                        'The Code',
                        'The Fast and the furious',
                        'The Jungle Book',
                        'The Lost City',
                        'The Malavita family',
                        'The Marathon Man',
                        'The Mummy - Returns',
                        'The Mummy - Tomb of the dragon',
                        'The Mummy Ultimate',
                        'The Schluempfe II',
                        'The Thrumann show',
                        'The Yes man',
                        'The bucket list',
                        'The devil wears Prada',
                        'The dictator',
                        'The equalizer',
                        'The expendables',
                        'The expendables 2',
                        'The five people you meet in heaven',
                        'The girl with the ear ring',
                        'The golden child',
                        'The good shepherd',
                        'The great dictator',
                        'The great mouse detective',
                        'The grey',
                        'The judge',
                        'The kings speech',
                        'The last unicorn',
                        'The name of the rose',
                        'The new world',
                        'The other guys',
                        'The pianist',
                        'The prince of Egypt',
                        'The princess and the frog',
                        'The reader',
                        'The remain of the day',
                        'The smurfs',
                        'The social network',
                        'The soloist',
                        'The story of us',
                        'The tourist',
                        'The whole nine yards',
                        'The whole nine yards II',
                        'The wild river',
                        'The womanizer',
                        'There is something about Mary',
                        'Thirsteen days',
                        'Thunderland',
                        'Tinker Bell',
                        'To Rome with love',
                        'Toy Story',
                        'Transcendence',
                        'Transformers III',
                        'Troy',
                        'Two weeks notice',
                        'Ugly Truth',
                        'Up',
                        'Vier Minuten',
                        'Virtuosity',
                        'Wag the dog',
                        'Walk the line',
                        'Wall Street',
                        'Wanted',
                        'War of the roses',
                        'War of worlds',
                        'West side history',
                        'Who Framed Roger Rabbit',
                        'Wild wild west',
                        'Willow',
                        'World war Z',
                        'Wrath of the Titans',
                        'X-men',
                        'Yoko',
                        'Young Frankenstein',
                        'Zombieland',
                        'Zookeeper',
                        'Zorba the Greek'
        );

        $query = 'INSERT INTO `films` (`id`, `name`, `image`, `description`, `slug`, `trailer`, `year`, `duration`, `fsk_id`, `language_id`, `category_id`, `created_at`, `updated_at`) VALUES';
        $start = 20;

        foreach ($allfilms as $film) {
            $film = $film . "($start, '$film', 'images/$film.jpg', ' Description.', '" . to_slug($film) . "', 'https://www.youtube.com/watch?v=gdUrdivQ4_M', '1988-01-01', '01:25:00', 3, 2, 4, '2016-08-31 22:00:00', '2016-09-14 22:00:00'),";
            ++$start;
        }

        function to_slug($film) {
            return strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $film)));
        }

        print_r($query . $film);
    }

}


